//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/input/Pinballinput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Pinballinput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Pinballinput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Pinballinput"",
    ""maps"": [
        {
            ""name"": ""action"",
            ""id"": ""a634609a-5b24-41a8-9aca-3260f705f1f9"",
            ""actions"": [
                {
                    ""name"": ""launch"",
                    ""type"": ""Button"",
                    ""id"": ""8c4ddb5a-399e-438d-9761-2c731de4c9eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""flipL"",
                    ""type"": ""Button"",
                    ""id"": ""63e20596-250d-4de2-8f3e-200c9575e277"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""flipR"",
                    ""type"": ""Button"",
                    ""id"": ""21e9bfec-5f22-40c3-84fa-624ef1541a21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b92a06ba-b10e-4684-bd3a-b6816412f354"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""launch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29861c4a-afa3-45c8-a68e-76f1169a994c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""flipL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44e268bf-abf9-4bce-955b-f626a90e0ce2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""flipR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // action
        m_action = asset.FindActionMap("action", throwIfNotFound: true);
        m_action_launch = m_action.FindAction("launch", throwIfNotFound: true);
        m_action_flipL = m_action.FindAction("flipL", throwIfNotFound: true);
        m_action_flipR = m_action.FindAction("flipR", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // action
    private readonly InputActionMap m_action;
    private List<IActionActions> m_ActionActionsCallbackInterfaces = new List<IActionActions>();
    private readonly InputAction m_action_launch;
    private readonly InputAction m_action_flipL;
    private readonly InputAction m_action_flipR;
    public struct ActionActions
    {
        private @Pinballinput m_Wrapper;
        public ActionActions(@Pinballinput wrapper) { m_Wrapper = wrapper; }
        public InputAction @launch => m_Wrapper.m_action_launch;
        public InputAction @flipL => m_Wrapper.m_action_flipL;
        public InputAction @flipR => m_Wrapper.m_action_flipR;
        public InputActionMap Get() { return m_Wrapper.m_action; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionActions set) { return set.Get(); }
        public void AddCallbacks(IActionActions instance)
        {
            if (instance == null || m_Wrapper.m_ActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActionActionsCallbackInterfaces.Add(instance);
            @launch.started += instance.OnLaunch;
            @launch.performed += instance.OnLaunch;
            @launch.canceled += instance.OnLaunch;
            @flipL.started += instance.OnFlipL;
            @flipL.performed += instance.OnFlipL;
            @flipL.canceled += instance.OnFlipL;
            @flipR.started += instance.OnFlipR;
            @flipR.performed += instance.OnFlipR;
            @flipR.canceled += instance.OnFlipR;
        }

        private void UnregisterCallbacks(IActionActions instance)
        {
            @launch.started -= instance.OnLaunch;
            @launch.performed -= instance.OnLaunch;
            @launch.canceled -= instance.OnLaunch;
            @flipL.started -= instance.OnFlipL;
            @flipL.performed -= instance.OnFlipL;
            @flipL.canceled -= instance.OnFlipL;
            @flipR.started -= instance.OnFlipR;
            @flipR.performed -= instance.OnFlipR;
            @flipR.canceled -= instance.OnFlipR;
        }

        public void RemoveCallbacks(IActionActions instance)
        {
            if (m_Wrapper.m_ActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActionActions instance)
        {
            foreach (var item in m_Wrapper.m_ActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActionActions @action => new ActionActions(this);
    public interface IActionActions
    {
        void OnLaunch(InputAction.CallbackContext context);
        void OnFlipL(InputAction.CallbackContext context);
        void OnFlipR(InputAction.CallbackContext context);
    }
}
